[package]
name = "gix-gxf"
version = "0.1.0"
edition = "2021"

[dependencies]
gix-common = { path = "../gix-common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
